DROP TABLE VACCINE_NOTES;
DROP SEQUENCE vaccine_notes_seq;


CREATE TABLE VACCINE_NOTES (
 
VN_NO		VARCHAR2(10)	NOT NULL,
BD_NO		VARCHAR2(10)	NOT NULL,
VC_NO		VARCHAR2(10)	NOT NULL,
VN_DATE		DATE	NOT NULL,



CONSTRAINT VACCINE_NOTES_PK PRIMARY KEY (VN_NO));

CREATE SEQUENCE vaccine_notes_seq
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


INSERT INTO VACCINE_NOTES VALUES ('VN'||LPAD(to_char(vaccine_notes_seq.NEXTVAL),8,'0'),'BD00000001','VC00000001',TO_DATE('2017-4-18','YYYY-MM-DD'));
INSERT INTO VACCINE_NOTES VALUES ('VN'||LPAD(to_char(vaccine_notes_seq.NEXTVAL),8,'0'),'BD00000001','VC00000002',TO_DATE('2017-5-01','YYYY-MM-DD'));

commit;